services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

script:
  - ./deployment/build_all.sh
  - docker images
  - ./scripts/verify_build.sh
  - docker run --rm qualix_guacd echo "done"
  - docker run --rm qualix_guacamole echo "done"

deploy:
  - provider: script
    script: ./deployment/push.sh $version
    on:
      branch: master
    after_deploy:
    - ./scripts/create_tar_package.sh /tmp/$TRAVIS_BUILD_ID
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: $bucket_name
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: /tmp/$TRAVIS_BUILD_ID
    on:
      branch: master