services:
  - docker
language: bash

env:
  global:
    - VERSION="1.0."$TRAVIS_JOB_ID
jobs:
  include:
    - stage: build and deploy docker image
      script:
      - ./deployment/build_all.sh
      - docker images
      - ./scripts/verify_build.sh
      - ./deployment/push.sh
    - stage: test
      script: 
      - docker run --rm $DOCKER_USERNAME/qualix_guacd:latest echo "done"
      - docker run --rm $DOCKER_USERNAME/qualix_guacamole:latest echo "done"
