services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

before_install:
  - source config/.dev.env

env:
  global:
    - BASE_VERSION=1.0


script:
  - ./deployment/build_all.sh
  - docker images
  - ./scripts/verify_build.sh
  - docker run --rm qualix_guacd echo "done"
  - docker run --rm qualix_guacamole echo "done"

deploy:
  provider: script
  script: ./deployment/push.sh $BASE_VERSION.$TRAVIS_BUILD_NUMBER
  on:
    branch: master