services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

script:
  - ./deployment/build_all.sh
  - docker images
  - ./scripts/verify_build.sh
  - docker run --rm qualix_guacd echo "done"
  - docker run --rm qualix_guacamole echo "done"

deploy:
  provider: script
  script: ./deployment/push.sh $version
  on:
    branch: master