services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

env:
  global:
    - TAR_PATH=$TRAVIS_BUILD_DIR

script:
  - ./deployment/build_all.sh
  - docker images
  - ./scripts/verify_build.sh
  - docker run --rm qualix_guacd echo "done"
  - docker run --rm qualix_guacamole echo "done"
  - ./scripts/create_tar_package.sh $TRAVIS_BUILD_DIR/$TRAVIS_BUILD_ID $version

deploy:
  - provider: script
    script: ./deployment/push.sh $version
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: $bucket_name
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: $TRAVIS_BUILD_DIR/$TRAVIS_BUILD_ID
    on:
      branch: master