services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

env:
  global:
    - BASE_REPO=quali


script:
  - ./deployment/build_all.sh
  - docker images
  - ./scripts/verify_build.sh
  - docker run --rm $BASE_REPO/qualix_guacd echo "done"
  - docker run --rm $BASE_REPO/qualix_guacamole echo "done"

deploy:
  provider: script
  script: ./deployment/push.sh $TRAVIS_BUILD_NUMBER
  on:
    branch: master