services:
  - docker
language: bash

branches:
  only:
  - master
  - develop

env:
  global:
    - VERSION="1.0."$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - stage: build and deploy docker image
      script:
      - ./deployment/build_all.sh
      - docker images
      - ./scripts/verify_build.sh
      - ./deployment/push.sh
    - stage: test
      script: 
      - docker run --rm $DOCKER_USERNAME/qualix_guacd:$VERSION echo "done"
      - docker run --rm $DOCKER_USERNAME/qualix_guacamole:$VERSION echo "done"
