version: "3.0"

services:
  guacamole:
    image: qualitesthub/qualix_guacamole:$TAG_GUACAMOLE
    container_name: guacamole
    networks:
      - qxnetwork
    depends_on:
      - guacd
    environment:
      - GUACAMOLE_HOME=/opt/guacamole/.guacamole
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    ports:
      - 8090:80
      - 8088:8080
      - 8443:443

  guacd:
    image: qualitesthub/qualix_guacd:$TAG_GUACD
    container_name: guacd
    networks:
      - qxnetwork
    environment:
      - GUACD_LOG_LEVEL=debug

networks:
  qxnetwork:

