version: "3.0"

services:
  guacamole:
    image: qualitesthub/qualix_guacamole:$TAG_GUACAMOLE
    networks:
      - qxnetwork
    depends_on:
      - guacd
    environment:
      - GUACAMOLE_HOME=/opt/guacamole/.guacamole
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    ports:
      - ${PORT_80}:80
      - ${PORT_8080}:8080
      - ${PORT_443}:443
    volumes:
      - files:${GUACAMOLE_HOME}/files
  guacd:
    image: qualitesthub/qualix_guacd:$TAG_GUACD
    networks:
      - qxnetwork
    environment:
      - GUACD_LOG_LEVEL=debug

networks:
  qxnetwork:

volumes:
  files:

